import type { ModelRuntime, ResolvedModelSpec } from "../types.ts"

/** Execution implementations understood by AgENV. */
export type ExecutionBackend = "sdk" | "legacy"

/** Providers/runtimes represented at the AgENV boundary. */
export type AgentProvider = ModelRuntime

/** Alias emphasizing that provider selection is also runtime selection here. */
export type ProviderRuntime = AgentProvider

export type AttemptTerminalStatus = "completed" | "failed" | "cancelled"

export type AgentEventType =
  | "started"
  | "assistant"
  | "tool"
  | "status"
  | "progress"
  | "completed"
  | "failed"
  | "cancelled"
  | "usage"

/** JSON-like provider information retained without importing a provider SDK. */
export type ProviderMetadata = Record<string, unknown>

/** A normalized error suitable for persistence and activity logs. */
export interface AgentAttemptError {
  message: string
  name?: string
  code?: string
  retryable?: boolean
  timedOut?: boolean
  diagnostic?: unknown
}

/** Token/cost information when a provider reports it. */
export interface AgentUsage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
  cachedInputTokens?: number
  cost?: number
  currency?: string
  [key: string]: unknown
}

/**
 * All data required to create one atomic provider attempt.
 *
 * `attemptId` must be new for every attempt, including an explicitly selected
 * fallback. `model` is already resolved, so adapters never need to infer a
 * provider/runtime or synthesize a runtime from a provider-specific model ID.
 */
export interface AttemptInput {
  repoRoot: string
  streamId: string
  batchId: string
  threadId: string
  workSessionId: string
  attemptId: string
  logicalAgent: string
  model: ResolvedModelSpec
  prompt: string
  title: string
  /** Included for persistence and diagnostics; SDK is the initial seam. */
  executionBackend?: ExecutionBackend
}

/**
 * Input used by the ordered-candidate helper before it assigns a fresh ID and
 * candidate model. It also accepts a complete AttemptInput for convenience,
 * but the helper always replaces `attemptId` and `model`.
 */
export type AttemptInputSeed = Omit<AttemptInput, "attemptId" | "model"> &
  Partial<Pick<AttemptInput, "attemptId" | "model">>

/**
 * Provider-native identifiers returned immediately after native startup.
 *
 * Adapters should return this value as soon as the provider creates its
 * session/agent, before `run` submits the prompt, so callers can persist the
 * IDs before any provider work begins.
 */
export interface NativeAttempt {
  provider: AgentProvider
  attemptId: string
  nativeSessionId?: string
  nativeRunId?: string
  metadata?: ProviderMetadata
}

interface AgentCorrelation {
  provider: AgentProvider
  attemptId: string
  workSessionId: string
  /** Stable event/result ID generated by AgENV or the adapter. */
  eventId: string
  timestamp: string
  /** Optional provider or executor correlation value. */
  correlationId?: string
  nativeSessionId?: string
  nativeRunId?: string
}

interface AgentEventBase extends AgentCorrelation {
  type: AgentEventType
  diagnostic?: unknown
}

export interface AgentStartedEvent extends AgentEventBase {
  type: "started"
  metadata?: ProviderMetadata
}

export interface AgentAssistantEvent extends AgentEventBase {
  type: "assistant"
  text?: string
  /** True when `text` is a delta rather than the complete assistant output. */
  delta?: boolean
}

export interface AgentToolEvent extends AgentEventBase {
  type: "tool"
  toolName?: string
  phase?: "started" | "updated" | "completed" | "failed"
  input?: unknown
  output?: unknown
}

export interface AgentStatusEvent extends AgentEventBase {
  type: "status"
  status: string
  message?: string
  progress?: number
}

export interface AgentProgressEvent extends AgentEventBase {
  type: "progress"
  progress?: number
  message?: string
}

export interface AgentCompletedEvent extends AgentEventBase {
  type: "completed"
  result?: unknown
}

export interface AgentFailedEvent extends AgentEventBase {
  type: "failed"
  error: AgentAttemptError
}

export interface AgentCancelledEvent extends AgentEventBase {
  type: "cancelled"
  reason?: string
}

export interface AgentUsageEvent extends AgentEventBase {
  type: "usage"
  usage: AgentUsage
}

/** Provider-neutral lifecycle events emitted by an adapter. */
export type AgentEvent =
  | AgentStartedEvent
  | AgentAssistantEvent
  | AgentToolEvent
  | AgentStatusEvent
  | AgentProgressEvent
  | AgentCompletedEvent
  | AgentFailedEvent
  | AgentCancelledEvent
  | AgentUsageEvent

interface AttemptResultBase extends AgentCorrelation {
  status: AttemptTerminalStatus
  providerMetadata?: ProviderMetadata
}

export interface CompletedAttemptResult extends AttemptResultBase {
  status: "completed"
  result?: unknown
}

export interface FailedAttemptResult extends AttemptResultBase {
  status: "failed"
  error: AgentAttemptError
}

export interface CancelledAttemptResult extends AttemptResultBase {
  status: "cancelled"
  reason?: string
  error?: AgentAttemptError
}

/** Terminal result for one atomic attempt. */
export type AttemptResult =
  | CompletedAttemptResult
  | FailedAttemptResult
  | CancelledAttemptResult

export type CancelStatus = "cancelled" | "already_terminal" | "not_found" | "failed"

/** Outcome of an explicit cancellation request. */
export interface CancelResult extends AgentCorrelation {
  status: CancelStatus
  cancelled: boolean
  acknowledged: boolean
  error?: AgentAttemptError
  providerMetadata?: ProviderMetadata
}

export type ReconciliationStatus =
  | "unknown"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"

/** Optional native-state lookup; this is not a conversation-resume API. */
export interface ReconciliationResult {
  provider: AgentProvider
  nativeSessionId: string
  nativeRunId?: string
  status: ReconciliationStatus
  timestamp: string
  attemptId?: string
  providerMetadata?: ProviderMetadata
  diagnostic?: unknown
}

/**
 * Provider-neutral adapter boundary for one atomic attempt.
 *
 * Provider SDK request/event types must remain inside the implementation of an
 * adapter. `run` intentionally takes a normal prompt and does not require an
 * async-prompt or conversation-resume capability.
 */
export interface AgentAttemptAdapter {
  readonly executionBackend: ExecutionBackend
  readonly provider: AgentProvider

  startAttempt(input: AttemptInput): Promise<NativeAttempt>
  run(attempt: NativeAttempt, prompt: string): Promise<AttemptResult>
  events(attempt: NativeAttempt): AsyncIterable<AgentEvent>
  cancel(attempt: NativeAttempt): Promise<CancelResult>
  close(): Promise<void>

  /** Optional native inspection/reconciliation, not conversation resume. */
  reconcile?(nativeSessionId: string): Promise<ReconciliationResult>
}
