/**
 * Workstream generation functions
 *
 * Creates workstream directories and scaffolds draft planning files on demand.
 */

import { existsSync, mkdirSync, readdirSync } from "fs"
import { join } from "path"
import type { StreamMetadata, GeneratedBy, ConsolidateError } from "./types.ts"
import { VERSION as WORKSTREAMS_VERSION } from "../version.ts"
import { getWorkDir } from "./repo.ts"
import {
  getOrCreateIndex,
  saveIndex,
  getNextOrderNumber,
  formatOrderNumber,
  atomicWriteFile,
} from "./index.ts"
import { toTitleCase, getDateString } from "./utils.ts"
import { parseStreamDocument } from "./stream-parser.ts"
import { createStructuredStorageWorkstreamRecord } from "./structured-storage.ts"
import { loadStructuredWorkspaceStateSync, replaceStructuredWorkspaceStateSync } from "./storage-adapter.ts"
import { loadSqliteStructuredStorageWorkspaceState } from "./sqlite-storage.ts"

/**
 * Generate the version string for templates
 */
function getVersionString(): string {
  return `@agenv/workstreams@${WORKSTREAMS_VERSION}`
}

export interface GenerateStreamArgs {
  name: string
  repoRoot: string
  stages?: number
}

export interface GenerateStreamResult {
  streamId: string
  streamPath: string
}

function getStageDirectoryName(stageNum: number): string {
  return stageNum.toString().padStart(2, "0")
}

function formatStageDirectoryLabel(stageLabel: number | string): string {
  return typeof stageLabel === "number" ? getStageDirectoryName(stageLabel) : stageLabel
}

/**
 * Generate stage-local REQUIREMENTS.md content.
 */
function generateStageRequirementsMd(stageLabel: number | string): string {
  const stageDir = formatStageDirectoryLabel(stageLabel)

  return `# Stage ${stageDir} Requirements

## Summary

<!-- Describe this stage's goal in freeform markdown. Do not use bullets in this section. -->

## Deliverables

<!-- Keep this section as bullets. List the concrete outputs this stage must produce. -->
- Replace with a concrete stage deliverable

## Dependencies

<!-- Keep this section as bullets. Reference repo-relative code paths in backticks, for example: \`packages/workstreams/src/lib/generate.ts\` -->
- \`packages/workstreams/src/lib/generate.ts\`

## Resources

<!-- Keep this section as bullets. Reference shared resources under \`resources/\` -->
- \`resources/example-notes.md\`
`
}

/**
 * Generate stage-local PLAN.md content.
 */
function generateStagePlanMd(stageLabel: number | string): string {
  const stageDir = formatStageDirectoryLabel(stageLabel)
  const now = getDateString()
  const version = getVersionString()

  return `# Stage ${stageDir} Plan

> **Stage:** ${stageDir} | **Created:** ${now} | **Generated by:** ${version}
> Rename this heading to something like \`# Stage ${stageDir} Implementation Plan\` so downstream tools preserve a meaningful stage name.

## Summary

<!-- High-level overview of what this stage accomplishes -->

## References

<!-- Source files, reasoning documents, tools used -->
- <!-- Add references here -->

## Questions

<!-- Unknowns, research to-dos as [ ] checkboxes -->
- [ ]

## Batches

### Batch 01: <!-- Batch Name -->

<!-- What this batch accomplishes -->

#### Thread 01: <!-- Thread Name -->

**Summary:**
<!-- Short description of this parallelizable work unit -->

**Details:**
<!-- Any content - implementation notes, dependencies, goals, code examples, etc. -->
`
}

function generateWorkstreamReadme(streamId: string, streamName: string): string {
  const titleName = toTitleCase(streamName)

  return `# ${titleName}

Stream ID: \`${streamId}\`

## Summary

<!-- Describe the overall workstream goal and context in freeform markdown. -->

## Deliverables

<!-- Keep this section as bullets. List the cross-stage outputs this workstream must produce. -->
- Replace with a concrete workstream deliverable

## Dependencies

<!-- Keep this section as bullets. Reference repo-relative code paths in backticks. -->
- \`packages/workstreams/src/lib/generate.ts\`

## Resources

<!-- Keep this section as bullets. Reference shared workstream files under \`resources/\` or \`docs/\`. -->
- \`resources/example-notes.md\`

## Initial Layout

- \`README.md\` — overall workstream context
- \`resources/\` — shared inputs gathered before stage planning
- \`docs/\` — supporting notes and drafts
- \`stages/\` — stage-specific planning and execution material

## Stage Planning Workflow

1. Capture shared context and reference material under \`resources/\` and \`docs/\`.
2. Update this \`README.md\` with the overall workstream context, deliverables, dependencies, and shared resources.
3. Run \`work plan create --stream "${streamId}" --stages <n>\` to scaffold stage directories under \`stages/\`.
4. For each stage, fill in \`REQUIREMENTS.md\`, \`PLAN.md\`, and \`specs/\`.
5. After plan or revision approval initializes execution, thread-specific \`WORK.md\` files are generated under \`stages/<stage-dir>/threads/<thread-id>/\`.

This workstream intentionally starts with shared root context plus empty stage scaffolding. There is no root \`REQUIREMENTS.md\` or \`PLAN.md\` in the supported model; stage planning lives under \`stages/<nn>/\`.
`
}

export function scaffoldPlanStages(repoRoot: string, streamId: string, numStages: number): {
  stagesPath: string
  stageCount: number
} {
  const stagesPath = join(getWorkDir(repoRoot), streamId, "stages")

  if (!existsSync(stagesPath)) {
    mkdirSync(stagesPath, { recursive: true })
  }

  const existingStageEntries = readdirSync(stagesPath)
  if (existingStageEntries.length > 0) {
    throw new Error(
      `stages/ for workstream "${streamId}" already contains stage content. Edit it manually instead of re-scaffolding.`,
    )
  }

  for (let stageNum = 1; stageNum <= numStages; stageNum++) {
    const stageDirName = getStageDirectoryName(stageNum)
    const stageDir = join(stagesPath, stageDirName)
    scaffoldStageDirectory(stageDir, stageDirName)
  }

  return {
    stagesPath,
    stageCount: numStages,
  }
}

export function scaffoldStageDirectory(stageDir: string, stageLabel: string): void {
  const stageSpecsDir = join(stageDir, "specs")
  const stageThreadsDir = join(stageDir, "threads")

  mkdirSync(stageDir, { recursive: true })
  mkdirSync(stageSpecsDir, { recursive: true })
  mkdirSync(stageThreadsDir, { recursive: true })
  atomicWriteFile(join(stageDir, "REQUIREMENTS.md"), generateStageRequirementsMd(stageLabel))
  atomicWriteFile(join(stageDir, "PLAN.md"), generateStagePlanMd(stageLabel))
}

/**
 * Generate REPORT.md template content directly from PLAN.md
 * This is used during stream creation before the stream is indexed
 * Falls back to simple template if PLAN.md can't be parsed (e.g., still a template)
 */
function generateReportMdTemplate(
  streamId: string,
  streamName: string,
  planContent: string,
  numStages: number,
): string {
  const errors: ConsolidateError[] = []
  const planDoc = parseStreamDocument(planContent, errors)

  const lines: string[] = []

  // Header
  lines.push(`# Report: ${toTitleCase(streamName)}`)
  lines.push("")
  lines.push(`> **Stream ID:** ${streamId} | **Reported:** ${getDateString()}`)
  lines.push("")

  // Summary section
  lines.push("## Summary")
  lines.push("<!-- High-level summary of what was achieved -->")
  lines.push("")

  // Accomplishments section
  lines.push("## Accomplishments")
  lines.push("")

  // Add a subsection for each stage
  // If PLAN.md parsed successfully, use actual stage names
  // Otherwise, use placeholder names
  if (planDoc && errors.length === 0 && planDoc.stages.length > 0) {
    for (const stage of planDoc.stages) {
      const stagePrefix = stage.id.toString().padStart(2, "0")
      lines.push(`### Stage ${stagePrefix}: ${stage.name}`)
      lines.push("<!-- What was accomplished in this stage -->")
      lines.push("")
      lines.push("#### Key Changes")
      lines.push("- {description}")
      lines.push("")
    }
  } else {
    // Fallback: generate template stages based on numStages
    for (let i = 1; i <= numStages; i++) {
      const stagePrefix = i.toString().padStart(2, "0")
      lines.push(`### Stage ${stagePrefix}: <!-- Stage Name -->`)
      lines.push("<!-- What was accomplished in this stage -->")
      lines.push("")
      lines.push("#### Key Changes")
      lines.push("- {description}")
      lines.push("")
    }
  }

  // File References section
  lines.push("## File References")
  lines.push("")
  lines.push("| File | Changes |")
  lines.push("|------|---------|")
  lines.push("| `path/to/file.ts` | Description of changes |")
  lines.push("")

  // Issues & Blockers section
  lines.push("## Issues & Blockers")
  lines.push("<!-- Any issues encountered, bugs found, or blockers hit -->")
  lines.push("")

  // Next Steps section
  lines.push("## Next Steps")
  lines.push("<!-- Recommended follow-up work -->")
  lines.push("")

  return lines.join("\n")
}

/**
 * Main workstream generation function
 *
 * Creates a new workstream with a minimal initial filesystem layout.
 */
export function generateStream(args: GenerateStreamArgs): GenerateStreamResult {
  const workDir = getWorkDir(args.repoRoot)

  // Ensure workstreams directory exists
  if (!existsSync(workDir)) {
    mkdirSync(workDir, { recursive: true })
  }

  // Get or create index
  const index = getOrCreateIndex(args.repoRoot)

  // Check if workstream with same name already exists
  const existingStream = index.streams.find((s) => s.name === args.name)
  if (existingStream) {
    throw new Error(
      `Workstream with name "${args.name}" already exists (${existingStream.id})`,
    )
  }

  // Generate stream ID
  const order = getNextOrderNumber(index)
  const streamId = `${formatOrderNumber(order)}-${args.name}`
  const streamPath = `work/${streamId}`
  const streamDir = join(workDir, streamId)

  // Create stream directory
  mkdirSync(streamDir, { recursive: true })

  // Create docs directory
  const docsDir = join(streamDir, "docs")
  mkdirSync(docsDir, { recursive: true })

  // Create resources directory
  const resourcesDir = join(streamDir, "resources")
  mkdirSync(resourcesDir, { recursive: true })

  // Create stages directory
  const stagesDir = join(streamDir, "stages")
  mkdirSync(stagesDir, { recursive: true })

  // Generate top-level README only; planning artifacts are created later.
  atomicWriteFile(join(streamDir, "README.md"), generateWorkstreamReadme(streamId, args.name))

  // Create stream metadata (without size)
  const now = new Date().toISOString()
  const generatedBy: GeneratedBy = {
    workstreams: WORKSTREAMS_VERSION,
  }

  const streamMetadata: StreamMetadata = {
    id: streamId,
    name: args.name,
    order,
    size: "medium", // Deprecated - will be removed
    session_estimated: {
      length: 4,
      unit: "session",
      session_minutes: [30, 45],
      session_iterations: [4, 8],
    },
    created_at: now,
    updated_at: now,
    path: streamPath,
    generated_by: generatedBy,
  }

  const sqliteWorkspaceState = loadSqliteStructuredStorageWorkspaceState(args.repoRoot)

  if (sqliteWorkspaceState) {
    const workspaceState = loadStructuredWorkspaceStateSync(args.repoRoot)
    workspaceState.workstreams.push(createStructuredStorageWorkstreamRecord(streamMetadata))
    replaceStructuredWorkspaceStateSync({
      repoRoot: args.repoRoot,
      workspaceState,
    })
  } else {
    index.streams.push(streamMetadata)
    saveIndex(args.repoRoot, index)
  }

  return {
    streamId,
    streamPath,
  }
}

/**
 * Create generate args
 */
export function createGenerateArgs(
  name: string,
  repoRoot: string,
  stages?: number,
): GenerateStreamArgs {
  return {
    name,
    repoRoot,
    stages,
  }
}
