// No SQL connection, schema, migration or legacy persistence is available.
export { unavailable as currentUser, unavailable as normalizeWorkstreamId, unavailable as flattenWorkstreamId,
  unavailable as branchForWorkstream, unavailable as saneDbPath, unavailable as resolveSaneIdentity,
  unavailable as assertSelectionSlot, unavailable as openSaneDb, unavailable as openSaneDbAtPath,
  unavailable as openInMemoryDb, unavailable as initSchema, unavailable as getWorkstreamImplementation,
  unavailable as setWorkstreamImplementation, unavailable as getSessionWorkstream, unavailable as bindSessionWorkstream,
  unavailable as upsertWorkstream, unavailable as getWorkstream, unavailable as getWorkstreamType,
  unavailable as listWorkstreams, unavailable as deleteWorkstream, unavailable as setCurrentWorkstream,
  unavailable as getCurrentWorkstream, unavailable as upsertSelection, unavailable as linkSelection,
  unavailable as listSelectionsBySlot, unavailable as getLatestSelection, unavailable as getSelection,
  unavailable as listSelections, unavailable as deleteSelection, unavailable as unlinkSelection,
  unavailable as upsertStateEntry, unavailable as getStateEntry, unavailable as listStateEntries,
  unavailable as deleteStateEntry, unavailable as recordApproval, unavailable as getApproval,
  unavailable as listApprovals, unavailable as deleteApproval, unavailable as registerResearchReport,
  unavailable as getResearchReport, unavailable as listResearchReports, unavailable as deleteResearchReport,
  unavailable as createJob, unavailable as getJob, unavailable as listJobs, unavailable as updateJobStatus,
  unavailable as completeAllJobs, unavailable as deleteJob, unavailable as upsertMerge, unavailable as getMerge,
  unavailable as recordMergeCommit, unavailable as deleteMerge, unavailable as listMutations,
  unavailable as jobStatusOrder } from "./unavailable.ts"
